### ISSUE TITLE
Bundler throwing errors and knocking classic notebook server over

### ISSUE THREAD

**Issue by psychemedia** [m-rossi/jupyter-docx-bundler#77]
I *think* this is a `jupyter-docx-bundler` issue: installing into classic notebook, it seems to throw a lot of errors the notebook log and cause a 500 error serving notebooks:

```
 HTTPServerRequest(protocol='http', host='localhost:8897', method='GET', uri='/notebooks/work/Untitled.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyter_docx_bundler/converters.py", line 3, in <module>
        from importlib.resources import files as resources_files
    ImportError: cannot import name 'files' from 'importlib.resources' (/usr/lib/python3.8/importlib/resources.py)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python3.8/dist-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/usr/local/lib/python3.8/dist-packages/notebook/base/handlers.py", line 516, in render_template
        return template.render(**ns)
      File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1304, in render
        self.environment.handle_exception()
      File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 925, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/usr/local/lib/python3.8/dist-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/usr/local/lib/python3.8/dist-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/usr/local/lib/python3.8/dist-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/usr/local/lib/python3.8/dist-packages/notebook/notebook/handlers.py", line 41, in get_frontend_exporters
        exporter_class = get_exporter(name)
      File "/usr/local/lib/python3.8/dist-packages/nbconvert/exporters/base.py", line 98, in get_exporter
        return entrypoints.get_single('nbconvert.exporters', name).load()
      File "/usr/local/lib/python3.8/dist-packages/entrypoints.py", line 82, in load
        mod = import_module(self.module_name)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/local/lib/python3.8/dist-packages/jupyter_docx_bundler/__init__.py", line 7, in <module>
        from . import converters
      File "/usr/local/lib/python3.8/dist-packages/jupyter_docx_bundler/converters.py", line 5, in <module>
        from importlib_resources import files as resources_files
    ModuleNotFoundError: No module named 'importlib_resources'
```

**Comment by m-rossi** [comment]
Could be true, as I started using `importlib.resources`/`importlib_resources` with the last version. Can you provide some details how you installed/updated jupyter-docx-bundler? As I can see from your log you are using Python 3.8. Normally, the package `importlib_resources` should have been installed during the update.

**Comment by psychemedia** [comment]
Simple install from pypi - `pip install jupyter-docx-bundler` and then just started the server. And yes, Python 3.8 on ubuntu 20.0.

**Comment by m-rossi** [comment]
Ouch, I can confirm that. Looks like
https://github.com/m-rossi/jupyter-docx-bundler/blob/68eb32814a2a97e63fea3d7cb8ffdf377a3acfd1/setup.py#L20-L21
did not work like expected and to an extend is the wrong package 😢 
You should fix your issue by manually installing importlib_resources:
```sh
pip install importlib-resources
```
I will try to release a new version in a few hours.

Thanks for the report!
